 # config/packages/vich_uploader.yaml

vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /uploads/reclamations
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

